### ISSUE TITLE
Unable to Start Up Server

### ISSUE THREAD

**Issue by davidkwong** [mattstyles/yeoman-angular-express-plus#1]
Hi There,

I tried to install accordingly to the instruction . But the server doesn't run after "grunt server". Everything else works !

Any clue ? T_T

using node 0.10.7

---

bower installing jquery#2.0.0
bower installing angular#1.0.7
bower installing json3#3.2.4
bower installing es5-shim#2.0.11
bower installing angular-resource#1.0.7
bower installing angular-cookies#1.0.7
bower installing angular-sanitize#1.0.7
bower installing bootstrap#2.3.2
bower installing font-awesome-more#aa00919881388c2f7a8da35c2029851d98aeaf38
bower installing modernizr#2.6.2
bower installing angular-socket-io#0.0.1
bower installing socket.io-client#0.9.11
bower installing angular-bootstrap#0.3.0
bower installing lodash#1.2.1
bower installing angular-mocks#1.0.7
bower installing angular-scenario#1.0.7

install task completed.
✔ seed install completed successfully
✔ precommit hook written successfully

Running "clean:server" (clean) task

Running "connect:test" (connect) task
Starting connect web server on 0.0.0.0:5001.

Running "karma:unit" (karma) task
INFO [karma]: Karma server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "/Users/david/Desktop/KTrade/test/mock/*_/_.js" does not match any file.
INFO [PhantomJS 1.9 (Mac)]: Connected on socket id q6tj-dHxx0b0CU14JKRL
PhantomJS 1.9 (Mac): Executed 2 of 2 SUCCESS (0.185 secs / 0.027 secs)

Running "clean:server" (clean) task

Running "less:dev" (less) task
File app/styles/css/main.css created.

Running "livereload-start" task
... Starting Livereload server on 35729 ...

Running "connect:livereload" (connect) task
Warning: yeoman is not defined Use --force to continue.

Aborted due to warnings.
David-Kwongs-MacBook-Air:KTrade david$ grunt server

> > Local Npm module "grunt-cli" not found. Is it installed?

Running "clean:server" (clean) task

Running "connect:test" (connect) task
Starting connect web server on 0.0.0.0:5001.

Running "karma:unit" (karma) task
INFO [karma]: Karma server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "/Users/david/Desktop/KTrade/test/mock/*_/_.js" does not match any file.
INFO [PhantomJS 1.9 (Mac)]: Connected on socket id D-7J_E2FAXswDNKdJU3N
PhantomJS 1.9 (Mac): Executed 2 of 2 SUCCESS (0.182 secs / 0.027 secs)

Running "clean:server" (clean) task

Running "less:dev" (less) task
File app/styles/css/main.css created.

Running "livereload-start" task
... Starting Livereload server on 35729 ...

Running "connect:livereload" (connect) task
Warning: yeoman is not defined Use --force to continue.

Aborted due to warnings.

**Comment by mattstyles** [comment]
Hi David,

Thanks for reporting the error, I'm not at a computer until tonight (UK time) but it looks like one of the last commits to master may have caused the issue. 

I suspect it's a config error, as a stopgap measure can you try changing the ref to yeoman in the livereload and connect tasks to yeomanconfig? I can't look at the code right now but I'm hoping that is the problem. 

—

**Comment by mattstyles** [comment]
Hi David,

Latest commit on to master should resolve this issue.  Please let me know if it doesn't, otherwise I'll close the issue.

Thanks

**Comment by davidkwong** [comment]
All Fixed Aright now !! You are awesome ! =D

**Comment by mattstyles** [comment]
Sweet, cheers dude!
