### ISSUE TITLE
Provide mongoDB setup and server starting   in the README

### ISSUE THREAD

**Issue by adardesign** [mattstyles/yeoman-angular-express-plus#3]

**Comment by mattstyles** [comment]
Howdy, yes, this is something that I have meant to be doing, along with better overall documentation.

The Readme is still accurate but hasn't been kept bang up to date with usage instructions for the later branches.

Top of the todo list, I'm hoping to get some stuff tidied up tonight (UK time), if not, weekend deadline.

**Comment by adardesign** [comment]
Thanks!

**Comment by mattstyles** [comment]
Hi, made some progress on the wiki, hard link to mongoDB setup is here https://github.com/mattstyles/yeoman-angular-express-plus/wiki/Mongo-Example

Still needs a little fleshing out as regards project organisation but that will probably end up living somewhere else in the wiki.

I'll close this issue but please let me know how you get on with the Mongo-Example and if you find any omissions, I proof-read in somewhat of a hurry.

**Comment by adardesign** [comment]
Thanks much!
